// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Whitelist is an autogenerated mock type for the Whitelist type
type Whitelist struct {
	mock.Mock
}

// Find provides a mock function with given fields: _a0
func (_m *Whitelist) Find(_a0 string) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewWhitelist creates a new instance of Whitelist. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWhitelist(t interface {
	mock.TestingT
	Cleanup(func())
}) *Whitelist {
	mock := &Whitelist{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
