name: On Pull Request

on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  approve:
    if: contains(github.event.pull_request.labels.*.name, 'auto-approve-me')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      - name: Run Integration Tests
        run: make test-integration

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - uses: blocky/actions/go-lint@main
        with:
          go-version-file: './go.mod'
          config: './configs/golangci.yaml'
          timeout: '5m'
