name: On Pull Request

on:
  push:
    branches:
      - 'main'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  approve:
    if: contains(github.event.pull_request.labels.*.name, 'auto-approve-me')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          go: 'true'

      - name: Run Unit Tests
        run: make test-integration

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          go: 'true'
          go-cache: 'false'

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.57.1
          args: --timeout=3m --config=./golangci.yaml
